use serde::{Deserialize, Serialize};

/// Session configuration for BFF authentication
///
/// Sessions are stored in Redis with tokens server-side.
/// Browser only receives an httpOnly session cookie.
///
/// # BFF Authentication Flow
/// 1. Login: BFF calls Auth Service, stores tokens in Redis, returns session cookie
/// 2. Request: BFF extracts session from cookie, adds Authorization header
/// 3. Refresh: BFF auto-refreshes expired tokens (transparent to frontend)
/// 4. Logout: BFF deletes Redis session, clears cookie
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct BffSessionConfig {
    /// Enable BFF session-based authentication
    /// When enabled, BFF manages tokens server-side and browser only has session cookie
    #[serde(default)]
    pub enabled: bool,

    /// Redis host for session storage (can be same as cache Redis)
    pub redis_host: String,

    /// Redis port for session storage
    pub redis_port: u16,

    /// Redis password for authentication (optional)
    /// If empty or not set, connects without authentication
    #[serde(default)]
    pub redis_password: Option<String>,

    /// Redis key prefix for sessions
    pub key_prefix: String,

    /// Session TTL in seconds (should match refresh token lifetime)
    pub ttl_secs: u64,

    /// Cookie name for session ID
    pub cookie_name: String,

    /// Cookie domain (empty = current domain)
    #[serde(default)]
    pub cookie_domain: String,

    /// Cookie path
    pub cookie_path: String,

    /// Cookie SameSite attribute: "strict", "lax", "none"
    pub cookie_same_site: String,

    /// Cookie Secure flag (should be true in production)
    pub cookie_secure: bool,

    /// Token refresh buffer in seconds (refresh this many seconds before expiry)
    pub refresh_buffer_secs: u64,

    /// Timeout for individual Redis operations in seconds
    /// CRITICAL: Prevents blocking requests when Redis is slow/unavailable
    pub operation_timeout_secs: u64,

    /// Token-free authentication mode (BFF-only pattern)
    ///
    /// When enabled:
    /// - Query rewriter does NOT inject accessToken/refreshToken/expiresIn fields
    /// - Auth interceptor creates sessions from user info (not token extraction)
    /// - Backend returns only { user: {...}, isNewUser: bool }
    /// - Session tokens are generated by BFF, not by backend
    ///
    /// Use this for products where the backend follows the BFF-only pattern
    /// and does not return JWT tokens in GraphQL responses.
    ///
    /// Default: false (legacy mode - expects tokens in response)
    #[serde(default)]
    pub token_free_auth: bool,

    /// NATS URL for session invalidation events
    ///
    /// When configured, the BFF subscribes to session invalidation events from the backend.
    /// When a user is deleted, banned, or otherwise invalidated, the backend publishes
    /// an event and the BFF clears all Redis sessions for that user.
    ///
    /// Format: "nats://host:port" (e.g., "nats://localhost:4222")
    /// Set via NATS_URL environment variable in production.
    ///
    /// Default: None (session invalidation disabled)
    #[serde(default)]
    pub nats_url: Option<String>,

    /// Configures which GraphQL mutations the BFF intercepts for session management.
    /// Defaults match the hardcoded behavior (Login*, Logout, VerifyMfaLogin, etc.)
    #[serde(default)]
    pub auth_interception: AuthInterceptionConfig,
}

impl Default for BffSessionConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            redis_host: "localhost".to_string(),
            redis_port: 6379,
            redis_password: None,
            key_prefix: "session:".to_string(),
            ttl_secs: 7776000,
            cookie_name: "session_id".to_string(),
            cookie_domain: String::new(),
            cookie_path: "/".to_string(),
            cookie_same_site: "strict".to_string(),
            cookie_secure: true,
            refresh_buffer_secs: 60,
            operation_timeout_secs: 2,
            token_free_auth: false,
            nats_url: None,
            auth_interception: AuthInterceptionConfig::default(),
        }
    }
}

/// Configures which GraphQL mutations the BFF intercepts for session management.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct AuthInterceptionConfig {
    /// Login mutation matching rules
    pub login: MutationMatcher,
    /// Logout mutation matching rules
    pub logout: MutationMatcher,
    /// MFA verify mutation matching rules
    pub mfa_verify: MutationMatcher,
    /// Magic link mutation matching rules
    pub magic_link: MutationMatcher,
    /// Start profile mutation matching rules
    pub start_profile: MutationMatcher,
    /// Token field names in GraphQL responses
    pub token_fields: TokenFieldConfig,
    /// Response field names where login data lives
    /// (e.g., `["login", "loginWithGoogle", "loginWithOAuthProvider"]`)
    pub login_response_fields: Vec<String>,
    /// Fields to strip from responses before returning to browser
    pub strip_fields: Vec<String>,
    /// Login mutation patterns for query rewriting
    /// (e.g., `["login(input:", "loginWithGoogle(", "loginWithOAuthProvider("]`)
    pub login_query_patterns: Vec<String>,
}

impl Default for AuthInterceptionConfig {
    fn default() -> Self {
        Self {
            login: MutationMatcher {
                operation_prefixes: vec!["login".to_string()],
                query_patterns: vec![
                    "mutation Login".to_string(),
                    "mutation login".to_string(),
                ],
                query_combined_patterns: vec![
                    ("login(".to_string(), "accessToken".to_string()),
                ],
            },
            logout: MutationMatcher {
                operation_prefixes: vec![],
                query_patterns: vec![
                    "mutation Logout".to_string(),
                    "mutation logout".to_string(),
                ],
                query_combined_patterns: vec![],
            },
            mfa_verify: MutationMatcher {
                operation_prefixes: vec![],
                query_patterns: vec![
                    "mutation VerifyMfaLogin".to_string(),
                    "mutation verifyMfaLogin".to_string(),
                    "verifyMfaLogin(".to_string(),
                ],
                query_combined_patterns: vec![],
            },
            magic_link: MutationMatcher {
                operation_prefixes: vec![],
                query_patterns: vec![
                    "mutation VerifyMagicLink".to_string(),
                    "mutation VerifyProviderMagicLink".to_string(),
                    "verifyMagicLink(".to_string(),
                ],
                query_combined_patterns: vec![],
            },
            start_profile: MutationMatcher {
                operation_prefixes: vec![],
                query_patterns: vec![
                    "mutation StartProfile".to_string(),
                    "startProfile(".to_string(),
                ],
                query_combined_patterns: vec![],
            },
            token_fields: TokenFieldConfig::default(),
            login_response_fields: vec![
                "login".to_string(),
                "loginWithGoogle".to_string(),
                "loginWithFacebook".to_string(),
                "loginWithOAuthProvider".to_string(),
            ],
            strip_fields: vec![
                "accessToken".to_string(),
                "refreshToken".to_string(),
                "expiresIn".to_string(),
            ],
            login_query_patterns: vec![
                "login(input:".to_string(),
                "login (input:".to_string(),
                "loginWithGoogle(".to_string(),
                "loginWithFacebook(".to_string(),
                "loginWithOAuthProvider(".to_string(),
            ],
        }
    }
}

/// Matching rules for a specific mutation type.
#[derive(Debug, Clone, Default, Deserialize, Serialize)]
#[serde(default)]
pub struct MutationMatcher {
    /// Operation name prefixes (matched case-insensitively via `starts_with`)
    pub operation_prefixes: Vec<String>,
    /// Query string patterns (matched with `.contains()`)
    pub query_patterns: Vec<String>,
    /// Combined patterns: both strings must appear in the query for a match
    pub query_combined_patterns: Vec<(String, String)>,
}

/// Token field name configuration for GraphQL response parsing.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct TokenFieldConfig {
    /// Access token field name (default: "accessToken")
    pub access_token: String,
    /// Refresh token field name (default: "refreshToken")
    pub refresh_token: String,
    /// Expires-in field name (default: "expiresIn")
    pub expires_in: String,
    /// User ID JSON path (default: "user.id")
    pub user_id_path: String,
}

impl Default for TokenFieldConfig {
    fn default() -> Self {
        Self {
            access_token: "accessToken".to_string(),
            refresh_token: "refreshToken".to_string(),
            expires_in: "expiresIn".to_string(),
            user_id_path: "user.id".to_string(),
        }
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CacheStrategy {
    /// GraphQL query pattern (e.g., "product.*", "user.cart")
    pub query_pattern: String,

    /// TTL in seconds for this pattern
    pub ttl_secs: u64,
}
